version: "3.9"
   
services:
  php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2345:80'
        volumes:
            - ./app/src:/var/www/html

  db:
    image: 'mariadb'
    restart: always
    env_file:
        - .env
    volumes:
        - ./dumpSql/data.sql:/docker-entrypoint-initdb.d/data.sql

  phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - db