version: "3.9"
   
services:
  db:
    image: 'mariadb'
    restart: always
    env_file:
        - .env
    volumes:
        - ./dumpSql/data.sql:/docker-entrypoint-initdb.d/data.sql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    environment:
      - .env
    depends_on:
      - db